# Generated by Django 4.0.5 on 2022-07-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('long_name', models.TextField()),
                ('business_summary', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=60)),
                ('website', models.TextField()),
                ('logo_url', models.TextField()),
                ('industry', models.CharField(max_length=30)),
                ('currency_unit', models.CharField(max_length=5)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=19)),
                ('regular_market_price', models.DecimalField(decimal_places=8, max_digits=19)),
                ('regular_market_open', models.DecimalField(decimal_places=8, max_digits=19)),
                ('regular_market_day_high', models.DecimalField(decimal_places=8, max_digits=19)),
                ('regular_market_previous_close', models.DecimalField(decimal_places=8, max_digits=19)),
                ('pre_market_price', models.DecimalField(decimal_places=8, max_digits=19)),
                ('day_low', models.DecimalField(decimal_places=8, max_digits=19)),
                ('fifty_day_average', models.DecimalField(decimal_places=8, max_digits=19)),
                ('two_hundred_day_average', models.DecimalField(decimal_places=8, max_digits=19)),
            ],
        ),
    ]
