# Generated by Django 4.0.5 on 2022-07-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stock_history_data_stock_histoy_data_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='histoy_data_labels',
            new_name='history_data_labels',
        ),
    ]
