# Generated by Django 4.0.5 on 2022-07-19 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_portfolio_customuser_profile_picture_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tagline',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('username', 'portfolio_name')},
        ),
    ]
