# Generated by Django 4.0.5 on 2022-07-20 00:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customuser_about_me_customuser_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=main.models.user_directory_path),
        ),
    ]
