# Generated by Django 4.0.5 on 2022-07-20 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_portfolio_id_alter_portfolio_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=19)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('username', 'portfolio_name')},
            },
        ),
        migrations.AlterField(
            model_name='trade',
            name='portfolio_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stockportfolio'),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
