# Generated by Django 4.0.5 on 2022-07-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
