# Generated by Django 4.0.5 on 2022-07-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_username_stockportfolio_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='start_balance',
            field=models.DecimalField(decimal_places=8, default=1000, max_digits=19),
            preserve_default=False,
        ),
    ]
