# Generated by Django 4.0.5 on 2022-07-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_stockportfolio_start_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='start_balance',
            field=models.DecimalField(decimal_places=8, max_digits=19, null=True),
        ),
    ]
