# Generated by Django 4.0.5 on 2022-07-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_stockportfolio_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockportfolio',
            old_name='portfolio_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together={('userid', 'name')},
        ),
    ]
