# Generated by Django 4.0.6 on 2022-08-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_stock_last_daily_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='business_summary',
            new_name='_business_summary',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='city',
            new_name='_city',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='country',
            new_name='_country',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='currency_unit',
            new_name='_currency_unit',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fifty_day_average',
            new_name='_fifty_day_average',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='industry',
            new_name='_industry',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='logo_url',
            new_name='_logo_url',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='long_name',
            new_name='_long_name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='state',
            new_name='_state',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='two_hundred_day_average',
            new_name='_two_hundred_day_average',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='website',
            new_name='_website',
        ),
    ]
