# Generated by Django 4.0.6 on 2022-08-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_business_summary_stock__business_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='_state',
            new_name='_state_location',
        ),
    ]
