# Generated by Django 4.0.6 on 2022-08-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename__state_stock__state_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='_logo_url',
            new_name='logo_url',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='_long_name',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='_website',
            new_name='website',
        ),
    ]
