# Generated by Django 4.0.6 on 2022-08-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_stock_last_price_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_history_update',
            field=models.DateTimeField(null=True),
        ),
    ]
