# Generated by Django 4.0.6 on 2022-08-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_stock_last_history_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='history_data_labels',
        ),
    ]
