# Generated by Django 4.0.6 on 2022-08-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_stock_history_data_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_history_update',
        ),
    ]
