# Generated by Django 4.0.6 on 2022-08-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_stock_last_history_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
