# Generated by Django 4.0.6 on 2022-08-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_userid_stockportfolio_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='portfolio_name',
            new_name='portfolio',
        ),
    ]
