# Generated by Django 4.0.6 on 2022-08-28 00:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_portfoliohistory_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliohistory',
            name='balance',
            field=models.DecimalField(decimal_places=8, max_digits=19),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='start_balance',
            field=models.DecimalField(decimal_places=8, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
